# -*- coding: utf-8 -*-
"""Basketball Motion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqDjwygi3appxvf_vHPY5A721d8DY4Id

----------------------------------------
-INSTALL DEPENDENCIES
----------------------------------------
"""

!pip install roboflow ultralytics opencv-python scikit-learn supervision
from roboflow import Roboflow
from ultralytics import YOLO
import cv2
import supervision as sv
from ultralytics import YOLO
from collections import defaultdict
from pathlib import Path

"""DOWNLOAD DATASET & TRAIN MODEL
------------------------------
"""

rf = Roboflow(api_key="2zWr1IWK0uNCszPDo3Ob")
project = rf.workspace("basketball-motion").project("basketball-motion-owdql")
version = project.version(5)  # V5 = 640 imgs (sharpest), V4 = 4000 imgs (stable ball/rim)
dataset = version.download("yolov8")

# Load a model
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)
model.train(data='/content/Basketball-Motion,-5/data.yaml', epochs=30, imgsz=640
)

"""IMPORTS & PARAMETERS  (edit paths here)
--------------------------------------
"""

# ---- Paths ----
MODEL_PATH   = "/content/runs/detect/train/weights/best.pt"
VIDEO_PATH   = "/content/Wemby_StpBK_Traject.mov"
OUTPUT_VIDEO = "/content/Wemby_StpBK_Traject_Overlay"

# ---- Detection ----
CONF_THRESH      = 0.05   # lower = more detections, more false positives
IMGSZ            = 640   # inference resolution (higher = better on small ball)

# ---- Ball tracking ----
TRAIL_LENGTH     = 35     # frames of fading dot trail behind ball
MIN_TRACK_LEN    = 8      # minimum detections to attempt a parabola fit
MAX_BALL_JUMP_PX = 160     # max px distance ball can move between frames without reset
BALL_MIN_Y_FRACTION = 0.10   # ignore balls detected in top 10% of frame (crowd/scoreboard)
BALL_MAX_Y_FRACTION = 0.90   # ignore balls below 90% (floor artifacts)

# ---- Shot detection ----
POST_APEX_FRAMES = 6      # how many frames after apex to accept rim overlap as a make
RIM_EXPAND_PX    = 20     # expand rim bbox by this many pixels for overlap check (forgiveness)

# ---- Overlay style ----
OVERLAY_DURATION = 90     # frames to show MADE / MISSED banner
ARC_COLOR_MAKE   = (0,   220,  80)   # green
ARC_COLOR_MISS   = (0,    60, 220)   # red
ARC_COLOR_LIVE   = (255, 255, 255)   # white (arc color before outcome is known)
TRAIL_COLOR      = (255, 200,   0)   # amber ball trail
RIM_COLOR        = (0,   165, 255)   # orange rim box

model = YOLO("/content/runs/detect/train/weights/best.pt")
results = model.predict(source="/content/Booker3.mov", save=True) #ENTER VIDEO PATH HERE
print(f"Model loaded from: {MODEL_PATH}")
print(f"Classes: {model.names}")

"""HELPER FUNCTIONS
------------------------------------------
"""

def get_video_info(path):
    """Return (fps, width, height, total_frames) for a video file."""
    cap = cv2.VideoCapture(path)
    fps    = cap.get(cv2.CAP_PROP_FPS) or 30.0
    w      = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h      = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total  = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    cap.release()
    return fps, w, h, total

def fit_parabola(frame_indices, ys, fps):
    """
    Fit a quadratic y(t) = a*t^2 + b*t + c to the ball's vertical pixel positions.
    Returns (poly_coefficients, poly1d_object, relative_times_array).
    """
    frames = np.array(frame_indices, dtype=float)
    times  = (frames - frames[0]) / fps
    poly   = np.polyfit(times, np.array(ys, dtype=float), 2)
    return poly, np.poly1d(poly), times

def predict_arc_points(frame_indices, xs, ys, fps, extend_frames=20):
    """
    Return a list of (px_x, px_y) pixel points tracing the fitted parabola,
    extended `extend_frames` into the future for predictive display.
    """
    poly, p, times = fit_parabola(frame_indices, ys, fps)
    frames = np.array(frame_indices, dtype=float)
    t_end  = (frames[-1] - frames[0]) / fps + extend_frames / fps
    ts     = np.linspace(0, t_end, num=80)
    pts    = []
    for t in ts:
        py = int(p(t))
        # linear x interpolation; clamp beyond last observed frame
        t_clamped = min(t, times[-1])
        px = int(np.interp(t_clamped, times, np.array(xs, dtype=float)))
        pts.append((px, py))
    return pts, poly

def check_made(frame_indices, xs, ys, fps, rim_bbox, poly):
    """
    Return (made: bool, made_frame: int | None).
    A make is confirmed when the ball passes through the rim bbox
    after the parabola apex, moving downward.
    """
    a, b, c = poly
    if abs(a) < 1e-6:
        return False, None

    frames  = np.array(frame_indices, dtype=float)
    times   = (frames - frames[0]) / fps
    t_apex  = -b / (2 * a)

    x1, y1, x2, y2 = rim_bbox
    # expand rim slightly
    x1 -= RIM_EXPAND_PX; y1 -= RIM_EXPAND_PX
    x2 += RIM_EXPAND_PX; y2 += RIM_EXPAND_PX

    apex_frame = frames[0] + t_apex * fps

    for i, t in enumerate(times):
        if t < t_apex:
            continue
        cx, cy = int(xs[i]), int(ys[i])
        vy = 2 * a * t + b   # positive vy = moving downward in image coords
        if x1 <= cx <= x2 and y1 <= cy <= y2 and vy > 0:
            fi = int(frame_indices[i])
            if fi - apex_frame <= POST_APEX_FRAMES:
                return True, fi
    return False, None

def draw_fading_trail(frame, trail_points, color=TRAIL_COLOR, max_radius=7):
    """Draw a fading dot trail. trail_points is a deque of (cx, cy) oldest→newest."""
    n = len(trail_points)
    for i, (cx, cy) in enumerate(trail_points):
        alpha  = (i + 1) / n
        radius = max(2, int(max_radius * alpha))
        bright = tuple(int(c * alpha) for c in color)
        cv2.circle(frame, (cx, cy), radius, bright, -1)

def draw_arc(frame, arc_pts, color, thickness=2):
    """Draw a smooth polyline arc from a list of (x, y) points."""
    for i in range(len(arc_pts) - 1):
        p1, p2 = arc_pts[i], arc_pts[i + 1]
        # skip points outside frame bounds
        h, w = frame.shape[:2]
        if not (0 <= p1[0] < w and 0 <= p1[1] < h):
            continue
        if not (0 <= p2[0] < w and 0 <= p2[1] < h):
            continue
        cv2.line(frame, p1, p2, color, thickness, lineType=cv2.LINE_AA)

def draw_make_miss_banner(frame, text, color, alpha=1.0):
    """Render a large centered MADE / MISSED banner with a semi-transparent background."""
    h, w = frame.shape[:2]
    font       = cv2.FONT_HERSHEY_DUPLEX
    font_scale = 2.8
    thickness  = 5
    (tw, th), baseline = cv2.getTextSize(text, font, font_scale, thickness)
    tx = (w - tw) // 2
    ty = int(h * 0.18)
    # dark pill background
    pad = 20
    overlay = frame.copy()
    cv2.rectangle(overlay,
                  (tx - pad, ty - th - pad),
                  (tx + tw + pad, ty + baseline + pad),
                  (20, 20, 20), -1)
    cv2.addWeighted(overlay, 0.55 * alpha, frame, 1 - 0.55 * alpha, 0, frame)
    # text
    cv2.putText(frame, text, (tx, ty), font, font_scale,
                tuple(int(c * alpha) for c in color), thickness, cv2.LINE_AA)

"""MAIN ANALYSIS PIPELINE
----------
"""

import json
import math
def run_analysis(video_path="/content/Wemby_StpBK_Traject.mov", output_path="/content/Wemby_StpBK_analyzed.mov"):

    fps, W, H, total_frames = get_video_info(video_path)
    print(f"Video: {total_frames} frames @ {fps:.1f} fps  |  {W}x{H}")

    cap = cv2.VideoCapture(video_path)
    out = cv2.VideoWriter(output_path,
                          cv2.VideoWriter_fourcc(*"mp4v"),
                          fps, (W, H))

    # --- ByteTrack setup via supervision ---
    tracker        = sv.ByteTrack()
    trace_annotator = sv.TraceAnnotator(
        color        = sv.ColorPalette.DEFAULT,
        thickness    = 2,
        trace_length = TRAIL_LENGTH,
    )
    box_annotator = sv.BoxAnnotator(thickness=1)
    label_annotator = sv.LabelAnnotator(text_scale=0.4, text_thickness=1)

    # --- State ---
    ball_trail      = []          # list of (cx, cy) for fading trail
    ball_track_fi   = []          # frame indices of ball detections
    ball_track_xs   = []          # ball cx values
    ball_track_ys   = []          # ball cy values
    rim_bbox        = None        # most recent rim detection
    shot_arc_pts    = None        # current arc to draw
    arc_color       = ARC_COLOR_LIVE
    overlay_text    = None        # "MADE" or "MISSED"
    overlay_color   = (255, 255, 255)
    overlay_frames  = 0           # countdown
    shot_log        = []          # list of dicts saved to JSON

    frame_idx = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # ── Run YOLO on this frame ───────────────────
        results = model(frame, conf=CONF_THRESH, imgsz=IMGSZ, verbose=False)[0]
        detections = sv.Detections.from_ultralytics(results)

        # ── ByteTrack update ───────────────────────
        detections = tracker.update_with_detections(detections)

        # ── Extract ball & rim from this frame ────────────
        best_ball = None
        all_ball_dets = []

        for i, class_id in enumerate(detections.class_id):
            class_name = model.names[class_id].lower()
            bbox = detections.xyxy[i]
            cx = int((bbox[0] + bbox[2]) / 2)
            cy = int((bbox[1] + bbox[3]) / 2)
            conf = float(detections.confidence[i])

            if class_name in ("ball", "basketball", "bball"):
                all_ball_dets.append((cx, cy, conf))

            if class_name in ("rim", "hoop", "basket"):
                rim_bbox = list(map(int, bbox))

        # ── Lock onto ball by proximity to last known position ───────────────
        if all_ball_dets:
            if ball_trail:
                # We have a history — pick the ball closest to last known position
                last_cx, last_cy = ball_trail[-1]
                candidates = [
                    (cx, cy, conf) for (cx, cy, conf) in all_ball_dets
                    if math.hypot(cx - last_cx, cy - last_cy) <= MAX_BALL_JUMP_PX
                ]
                if candidates:
                    # Among valid candidates, take highest confidence
                    best_ball = max(candidates, key=lambda x: x[2])[:2]
                else:
                    # Ball jumped too far — likely a cut/new play, reset track
                    best_ball = max(all_ball_dets, key=lambda x: x[2])[:2]
                    ball_trail.clear()
                    ball_track_fi.clear()
                    ball_track_xs.clear()
                    ball_track_ys.clear()
            else:
                # No history yet — take highest confidence to bootstrap
                best_ball = max(all_ball_dets, key=lambda x: x[2])[:2]

        ball_det = best_ball # Assign best_ball to ball_det for subsequent use

        # ── Update ball trail and track ───────────────────────
        if ball_det:
            cx, cy = ball_det
            ball_trail.append((cx, cy))
            if len(ball_trail) > TRAIL_LENGTH:
                ball_trail.pop(0)

            ball_track_fi.append(frame_idx)
            ball_track_xs.append(cx)
            ball_track_ys.append(cy)

            # Keep track window: drop oldest points if track grows very long
            # (prevents stale trajectory from old shot polluting new one)
            MAX_TRACK = 90
            if len(ball_track_fi) > MAX_TRACK:
                ball_track_fi = ball_track_fi[-MAX_TRACK:]
                ball_track_xs = ball_track_xs[-MAX_TRACK:]
                ball_track_ys = ball_track_ys[-MAX_TRACK:]

        # ── Fit parabola and check for shot when we have enough points ─────
        if len(ball_track_fi) >= MIN_TRACK_LEN:
            arc_pts, poly = predict_arc_points(
                ball_track_fi, ball_track_xs, ball_track_ys, fps
            )
            shot_arc_pts = arc_pts

            # Check make/miss only if we have a rim and haven't just fired a banner
            if rim_bbox is not None and overlay_frames == 0:
                made, made_frame = check_made(
                    ball_track_fi, ball_track_xs, ball_track_ys,
                    fps, rim_bbox, poly
                )
                if made_frame is not None:
                    label        = "MADE" if made else "MISSED"
                    arc_color    = ARC_COLOR_MAKE if made else ARC_COLOR_MISS
                    overlay_text  = label
                    overlay_color = arc_color
                    overlay_frames = OVERLAY_DURATION
                    shot_log.append({
                        "frame":      made_frame,
                        "result":     label,
                        "ball_pos":   [ball_track_xs[-1], ball_track_ys[-1]],
                        "rim_bbox":   rim_bbox,
                    })
                    print(f"  Shot detected @ frame {made_frame}: {label}")
                    # Reset track so we don't re-trigger on same shot
                    ball_track_fi.clear()
                    ball_track_xs.clear()
                    ball_track_ys.clear()
                    shot_arc_pts = None

        # ── Draw supervision player boxes + traces ─────────────
        labels = [
            f"{model.names[cid]} {conf:.2f}"
            for cid, conf in zip(detections.class_id, detections.confidence)
        ]
        frame = trace_annotator.annotate(frame, detections)
        frame = box_annotator.annotate(frame, detections)
        frame = label_annotator.annotate(frame, detections, labels=labels)

        # ── Draw rim box ──────────────────────────
        if rim_bbox is not None:
            x1, y1, x2, y2 = rim_bbox
            cv2.rectangle(frame, (x1, y1), (x2, y2), RIM_COLOR, 2)
            cv2.putText(frame, "RIM", (x1, y1 - 8),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.55, RIM_COLOR, 2)

        # ── Draw ball trail ───────────────────
        draw_fading_trail(frame, ball_trail)

        # ── Draw shot arc ───────────────
        if shot_arc_pts:
            draw_arc(frame, shot_arc_pts, arc_color)

        # ── Draw make/miss banner ───────────
        if overlay_frames > 0:
            # fade out in last 30 frames
            alpha = min(1.0, overlay_frames / 30.0)
            draw_make_miss_banner(frame, overlay_text, overlay_color, alpha)
            overlay_frames -= 1
            if overlay_frames == 0:
                shot_arc_pts = None
                arc_color    = ARC_COLOR_LIVE

        # ── Frame counter ───────────
        cv2.putText(frame, f"Frame {frame_idx}", (12, H - 14),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (180, 180, 180), 1)

        out.write(frame)
        frame_idx += 1

        if frame_idx % 100 == 0:
            print(f"  Processed {frame_idx}/{total_frames} frames...")

    cap.release()
    out.release()
    print(f"\nDone. Output saved to: {output_path}")

    # ── Save shot log to JSON ─────────────────
    log_path = str(Path(output_path).with_suffix(".json"))
    with open(log_path, "w") as f:
        json.dump({"video": Path(video_path).name, "fps": fps, "shots": shot_log}, f, indent=2)
    print(f"Shot log saved to: {log_path}")

    return shot_log

"""RUN FOR OUTPUTS HERE
--------------------
"""

import numpy as np

shot_results = run_analysis("/content/Wemby_StpBK_Traject.mov", "/content/Wemby_StpBK_analyzed.mov")

print(f"\n=== Summary: {len(shot_results)} shot(s) detected ===")
for i, s in enumerate(shot_results):
    print(f"  Shot {i+1}: {s['result']}  (frame {s['frame']})")